### ISSUE TITLE
EC Service Helmcharts - enhancements

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [EC-Release/helmcharts#50]
As per discussion on Apr 05, following changes to be done for ec service helm charts - 

- Add health liveness and readiness probe
- update mount path to svc_id folder. See example below for current vs proposed
- Add volume and mounts for ConfigMap for ec root certs (service.cer and service.key). ConfigMap name must be configurable from values.yaml
  - /root/service1.1
- Default replicas to 2 and should be configurable
- Flexibility to add new annotation to ingress
- Sample/example values.yaml for ci, preprod and prod
- Flexibility for ext ingress
- POC - Possibility to check if component exists or not before deploying service

-- current
```
  volumeMounts:
    - name: svc-mount
       mountPath: /root/svcs
       subPath: preprod/svcs/
```
-- proposed
```
  volumeMounts:
    - name: svc-mount
       mountPath: /root/svcs
       subPath: preprod/svcs/{svc-id}
```
